export const metadata = {
  title: {
    default: 'About',
  },
  description: 'Generated by create next app',
};

export default function AboutPage() {
  return <div>This is my about page.</div>;
}
